version: "3"

services:
  db:
    image: mysql:8.0
    ports:
      - "3315:3306"
    volumes:
      - ./containers/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "cms"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_HOST: "%"
    networks:
      - cms_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 30s

  xmr:
    image: ghcr.io/xibosignage/xibo-xmr:develop
    ports:
      - "9505:9505"
    environment:
      XMR_DEBUG: "true"
      IPV6PUBSUPPORT: "false"
    networks:
      - cms_network

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/var/www/cms
    ports:
      - "80:80"
    environment:
      CMS_DEV_MODE: "true"
      MYSQL_DATABASE: "cms"
      MYSQL_HOST: "db"  
    depends_on:
      - db
    networks:
      - cms_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  memcached:
    image: memcached:alpine
    command: memcached -m 64  
    networks:
      - cms_network
    healthcheck:
      test: ["CMD", "memcached", "-h"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  swagger:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://localhost/swagger.json
    networks:
      - cms_network

  quickchart:
    image: ianw/quickchart
    networks:
      - cms_network

networks:
  cms_network:
    driver: bridge
